git:
  pagers:
    - useExternalDiffGitConfig: true
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  autoStageResolvedConflicts: true
  overrideGpg: true
  disableForcePushing: false
  parseEmoji: true
  truncateCopiedCommitHashesTo: 12
  # branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName} --}
  # allBranchesLogCmds:
  #   - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
os:
  # edit: 'if ($env.NVIM? | is-empty) { nvim -- {{filename}} } else { nvim --server $env.NVIM --remote-send "q"; nvim --server $env.NVIM --remote-tab {{filename}} }'
  # editAtLine: 'if ($env.NVIM? | is-empty) { nvim +{{line}} -- {{filename}} } else { nvim --server $env.NVIM --remote-send "q"; nvim --server $env.NVIM --remote-tab {{filename}}; nvim --server $env.NVIM --remote-send ":{{line}}<CR>" }'
  # openDirInEditor: 'if ($env.NVIM? | is-empty) { nvim -- {{dir}} } else { nvim --server $env.NVIM --remote-send "q"; nvim --server $env.NVIM --remote-tab {{dir}} }'
  open: "xdg-open {{filename}}"
  openLink: "xdg-open {{link}}"
gui:
  shortTimeFormat: "15:04"
