[user]
name = "mirsella"
email = "mirsella@protonmail.com"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ":builtin"

[experimental-advance-branches]
enabled-branches = ["glob:*"]

[revsets]
log = "present(@) | ancestors(immutable_heads().., 3) | present(trunk())"

[aliases]
l = ["log"]
p = ["git push"]
n = ["new"]
di = ["diff"]
d = ["describe"]
c = ["commit"]
